// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddError(arg1) {
  return window['go']['dao']['NoteDao']['AddError'](arg1);
}

export function AddNote(arg1) {
  return window['go']['dao']['NoteDao']['AddNote'](arg1);
}

export function AfterInitialize(arg1) {
  return window['go']['dao']['NoteDao']['AfterInitialize'](arg1);
}

export function Apply(arg1) {
  return window['go']['dao']['NoteDao']['Apply'](arg1);
}

export function Assign(arg1) {
  return window['go']['dao']['NoteDao']['Assign'](arg1);
}

export function Association(arg1) {
  return window['go']['dao']['NoteDao']['Association'](arg1);
}

export function Attrs(arg1) {
  return window['go']['dao']['NoteDao']['Attrs'](arg1);
}

export function AutoMigrate(arg1) {
  return window['go']['dao']['NoteDao']['AutoMigrate'](arg1);
}

export function Begin(arg1) {
  return window['go']['dao']['NoteDao']['Begin'](arg1);
}

export function BindVarTo(arg1, arg2, arg3) {
  return window['go']['dao']['NoteDao']['BindVarTo'](arg1, arg2, arg3);
}

export function Callback() {
  return window['go']['dao']['NoteDao']['Callback']();
}

export function Clauses(arg1) {
  return window['go']['dao']['NoteDao']['Clauses'](arg1);
}

export function Commit() {
  return window['go']['dao']['NoteDao']['Commit']();
}

export function Connection(arg1) {
  return window['go']['dao']['NoteDao']['Connection'](arg1);
}

export function Count(arg1) {
  return window['go']['dao']['NoteDao']['Count'](arg1);
}

export function Create(arg1) {
  return window['go']['dao']['NoteDao']['Create'](arg1);
}

export function CreateInBatches(arg1, arg2) {
  return window['go']['dao']['NoteDao']['CreateInBatches'](arg1, arg2);
}

export function DataTypeOf(arg1) {
  return window['go']['dao']['NoteDao']['DataTypeOf'](arg1);
}

export function Debug() {
  return window['go']['dao']['NoteDao']['Debug']();
}

export function DefaultValueOf(arg1) {
  return window['go']['dao']['NoteDao']['DefaultValueOf'](arg1);
}

export function Delete(arg1, arg2) {
  return window['go']['dao']['NoteDao']['Delete'](arg1, arg2);
}

export function DeleteNote(arg1) {
  return window['go']['dao']['NoteDao']['DeleteNote'](arg1);
}

export function Distinct(arg1) {
  return window['go']['dao']['NoteDao']['Distinct'](arg1);
}

export function Done(arg1) {
  return window['go']['dao']['NoteDao']['Done'](arg1);
}

export function EditRank(arg1) {
  return window['go']['dao']['NoteDao']['EditRank'](arg1);
}

export function Exec(arg1, arg2) {
  return window['go']['dao']['NoteDao']['Exec'](arg1, arg2);
}

export function Explain(arg1, arg2) {
  return window['go']['dao']['NoteDao']['Explain'](arg1, arg2);
}

export function Find(arg1, arg2) {
  return window['go']['dao']['NoteDao']['Find'](arg1, arg2);
}

export function FindInBatches(arg1, arg2, arg3) {
  return window['go']['dao']['NoteDao']['FindInBatches'](arg1, arg2, arg3);
}

export function First(arg1, arg2) {
  return window['go']['dao']['NoteDao']['First'](arg1, arg2);
}

export function FirstOrCreate(arg1, arg2) {
  return window['go']['dao']['NoteDao']['FirstOrCreate'](arg1, arg2);
}

export function FirstOrInit(arg1, arg2) {
  return window['go']['dao']['NoteDao']['FirstOrInit'](arg1, arg2);
}

export function Get(arg1) {
  return window['go']['dao']['NoteDao']['Get'](arg1);
}

export function GetNotes() {
  return window['go']['dao']['NoteDao']['GetNotes']();
}

export function Group(arg1) {
  return window['go']['dao']['NoteDao']['Group'](arg1);
}

export function Having(arg1, arg2) {
  return window['go']['dao']['NoteDao']['Having'](arg1, arg2);
}

export function Initialize(arg1) {
  return window['go']['dao']['NoteDao']['Initialize'](arg1);
}

export function InnerJoins(arg1, arg2) {
  return window['go']['dao']['NoteDao']['InnerJoins'](arg1, arg2);
}

export function InstanceGet(arg1) {
  return window['go']['dao']['NoteDao']['InstanceGet'](arg1);
}

export function InstanceSet(arg1, arg2) {
  return window['go']['dao']['NoteDao']['InstanceSet'](arg1, arg2);
}

export function Joins(arg1, arg2) {
  return window['go']['dao']['NoteDao']['Joins'](arg1, arg2);
}

export function Last(arg1, arg2) {
  return window['go']['dao']['NoteDao']['Last'](arg1, arg2);
}

export function Limit(arg1) {
  return window['go']['dao']['NoteDao']['Limit'](arg1);
}

export function MapColumns(arg1) {
  return window['go']['dao']['NoteDao']['MapColumns'](arg1);
}

export function Migrator() {
  return window['go']['dao']['NoteDao']['Migrator']();
}

export function Model(arg1) {
  return window['go']['dao']['NoteDao']['Model'](arg1);
}

export function Name() {
  return window['go']['dao']['NoteDao']['Name']();
}

export function Not(arg1, arg2) {
  return window['go']['dao']['NoteDao']['Not'](arg1, arg2);
}

export function Offset(arg1) {
  return window['go']['dao']['NoteDao']['Offset'](arg1);
}

export function Omit(arg1) {
  return window['go']['dao']['NoteDao']['Omit'](arg1);
}

export function Or(arg1, arg2) {
  return window['go']['dao']['NoteDao']['Or'](arg1, arg2);
}

export function Order(arg1) {
  return window['go']['dao']['NoteDao']['Order'](arg1);
}

export function Pluck(arg1, arg2) {
  return window['go']['dao']['NoteDao']['Pluck'](arg1, arg2);
}

export function Preload(arg1, arg2) {
  return window['go']['dao']['NoteDao']['Preload'](arg1, arg2);
}

export function QuoteTo(arg1, arg2) {
  return window['go']['dao']['NoteDao']['QuoteTo'](arg1, arg2);
}

export function Raw(arg1, arg2) {
  return window['go']['dao']['NoteDao']['Raw'](arg1, arg2);
}

export function Rollback() {
  return window['go']['dao']['NoteDao']['Rollback']();
}

export function RollbackTo(arg1) {
  return window['go']['dao']['NoteDao']['RollbackTo'](arg1);
}

export function Row() {
  return window['go']['dao']['NoteDao']['Row']();
}

export function Rows() {
  return window['go']['dao']['NoteDao']['Rows']();
}

export function Save(arg1) {
  return window['go']['dao']['NoteDao']['Save'](arg1);
}

export function SavePoint(arg1) {
  return window['go']['dao']['NoteDao']['SavePoint'](arg1);
}

export function Scan(arg1) {
  return window['go']['dao']['NoteDao']['Scan'](arg1);
}

export function ScanRows(arg1, arg2) {
  return window['go']['dao']['NoteDao']['ScanRows'](arg1, arg2);
}

export function Scopes(arg1) {
  return window['go']['dao']['NoteDao']['Scopes'](arg1);
}

export function Select(arg1, arg2) {
  return window['go']['dao']['NoteDao']['Select'](arg1, arg2);
}

export function Session(arg1) {
  return window['go']['dao']['NoteDao']['Session'](arg1);
}

export function Set(arg1, arg2) {
  return window['go']['dao']['NoteDao']['Set'](arg1, arg2);
}

export function SetupJoinTable(arg1, arg2, arg3) {
  return window['go']['dao']['NoteDao']['SetupJoinTable'](arg1, arg2, arg3);
}

export function Table(arg1, arg2) {
  return window['go']['dao']['NoteDao']['Table'](arg1, arg2);
}

export function Take(arg1, arg2) {
  return window['go']['dao']['NoteDao']['Take'](arg1, arg2);
}

export function ToSQL(arg1) {
  return window['go']['dao']['NoteDao']['ToSQL'](arg1);
}

export function Transaction(arg1, arg2) {
  return window['go']['dao']['NoteDao']['Transaction'](arg1, arg2);
}

export function Unscoped() {
  return window['go']['dao']['NoteDao']['Unscoped']();
}

export function Update(arg1, arg2) {
  return window['go']['dao']['NoteDao']['Update'](arg1, arg2);
}

export function UpdateColumn(arg1, arg2) {
  return window['go']['dao']['NoteDao']['UpdateColumn'](arg1, arg2);
}

export function UpdateColumns(arg1) {
  return window['go']['dao']['NoteDao']['UpdateColumns'](arg1);
}

export function Updates(arg1) {
  return window['go']['dao']['NoteDao']['Updates'](arg1);
}

export function Use(arg1) {
  return window['go']['dao']['NoteDao']['Use'](arg1);
}

export function Where(arg1, arg2) {
  return window['go']['dao']['NoteDao']['Where'](arg1, arg2);
}

export function WithContext(arg1) {
  return window['go']['dao']['NoteDao']['WithContext'](arg1);
}
